test: &default

  # Credentials for REST APIs
  client_id: AWMhehAAxZ7i8Xl7lqsKPytpzGkp-4COODbMu_yykj7t6PzZfu-DGhPhpXyp
  client_secret: EDOrhBCZSwMarmOZcwO2Oj3Xcxu-EJmqeE6ax8wNluCVMcdpaLNN6SVYo1M9

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

development:
  <<: *default

production:
  <<: *default
  mode: live
